name: Release

on:
  issue_comment:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Analyse Comment
        id: analyse_comment
        uses: karlhulme/github-action-analyse-issue-comment@master
        with:
          authorisedLoginsCsv: karlhulme
          commentJson: ${{toJson(github.event.comment)}}
      - name: Clone repo
        if: steps.analyse_comment.outputs.instruction == 'release'
        uses: actions/checkout@v1
#       - name: Setup Node.js 12
#         uses: actions/setup-node@v1
#         with:
#           node-version: 12
#           registry-url: https://registry.npmjs.org/
#       - name: Install deps and run tests
#         run: |
#           npm ci
#           npm test
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.npm_token}}
