name: Release

on:
  issue_comment:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Add Comment
        uses: karlhulme/github-action-create-issue-comment@master
        with:
          issueNumber: ${{ github.event.issue.number }}
          body: ${{ format('You said {0}', github.event.comment.body) }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
