name: Release

on:
  issue_comment:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Add Comment
        uses: karlhulme/github-action-create-issue-comment@master
        with:
          issueNumber: 5
          body: I was added by a workflow
        env:
          GITHUB_TOKEN: ${{ github.token }}
