name: Release

on:
  issue_comment:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Release
        uses: karlhulme/github-action-prepare-release@master
        with:
          branchName: master
        env:
          GITHUB_TOKEN: ${{ github.token }}
